### ISSUE TITLE
Type error - Parameter url must be a string : not undefined

### ISSUE THREAD

**Issue by jfrieu** [ibm-watson-data-lab/watson-ml-scoring-demo#1]
Hello Mark, thanks for this work and lib
However I have trouble running the sample as explained in the 
https://medium.com/ibm-watson-data-lab/deploying-a-simple-machine-learning-app-with-node-js-and-watson-ml-96afdb6f7819
I am not using Part 2 for the model, I have a well defined and deployed model (Python), no issue there
I just want to use the HTML client and NodeJS server side / API to access the published model.

I placed some console.log statements in the WatsonMLScoringEndpoint to try to understand what is going on, however I am not a developer and I am reaching my limits.
All parameters WMLxx defined in .env file

-------------- _getWatsonMLAccessToken 
_getWatsonMLAccessToken : https://ibm-watson-ml.mybluemix.net/v3/identity/token
-------------- _getWatsonMLAccessToken 
_getWatsonMLAccessToken : https://ibm-watson-ml.mybluemix.net/v3/identity/token
_loadDeployments : https://ibm-watson-ml.mybluemix.net/v3/wml_instances/7f2d88d2-84f4-4136-ad1c-8318051c8263/published_models/06dd009c-7b3e-4d32-aa2c-c1974caa001e/deployments
-------------- Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0 ..etc...
then 
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at dispatchHttpRequest (C:\Users\IBM_ADMIN\Desktop\IBM Divers\TechAcademy Data Dealer\wmldatadealersdemo\node_modules\axios\lib\adapters\http.js:57:22)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\IBM_ADMIN\Desktop\IBM Divers\TechAcademy Data Dealer\wmldatadealersdemo\node_modules\axios\lib\adapters\http.js:18:10)
    at dispatchRequest (C:\Users\IBM_ADMIN\Desktop\IBM Divers\TechAcademy Data Dealer\wmldatadealersdemo\node_modules\axios\lib\core\dispatchRequest.js:59:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Not caught in log but displayed in the cmd console when running node app ..
(node:11344) UnhandledPromieRejectionWarning : Error: "Value" required in setHeader("Authorization",value)

![errornode](https://user-images.githubusercontent.com/8265450/41399965-03774f84-6fbc-11e8-9a26-10c388596463.JPG)

Token is provided, but seems url not defined ...

Thx

**Comment by jainshikha** [comment]
+1
